# Generated by Django 4.0.6 on 2022-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.IntegerField(db_column='class')),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=2048)),
                ('keywords', models.TextField()),
                ('first_par', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='UnVisitedPageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitedPageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
    ]
